import os
from dotenv import load_dotenv
from groq import Groq

load_dotenv()
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

# 1. Read the generated tests (output of the first agent)
with open("test_generated.py", "r") as f:
    generated_tests = f.read()

# 2. Also read the original source code, so the reviewer has context
with open("sample_code.py", "r") as f:
    source_code = f.read()

# 3. Build the review prompt
review_prompt = f"""You are a senior Python code reviewer.
Below is a source file and a pytest test file generated by another AI for it.

Review the test file for two types of issues:
1. Mechanical errors (e.g. missing imports, syntax errors).
2. Logical errors (e.g. tests that assume the source code raises an error 
   it never actually raises).

Source code:
{source_code}

Generated tests:
{generated_tests}

Respond in this exact format:
ISSUES FOUND:
- (list each issue on its own line, or write "None" if there are no issues)

CORRECTED TEST FILE:
(output the full corrected pytest file here, ready to run. 
Do NOT wrap it in markdown code blocks or triple backticks.)
"""

response = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[{"role": "user", "content": review_prompt}]
)

review_result = response.choices[0].message.content

# 1. Save the full review (issues + corrected code) as-is, for reference
with open("review_report.md", "w") as f:
    f.write(review_result)

# 2. Extract just the corrected test file (everything after "CORRECTED TEST FILE:")
if "CORRECTED TEST FILE:" in review_result:
    corrected_code = review_result.split("CORRECTED TEST FILE:")[1].strip()
else:
    corrected_code = ""

# 3. Clean up markdown code fences if present
if corrected_code.startswith("```"):
    lines = corrected_code.split("\n")
    lines = lines[1:]  # remove opening ```python line
    if lines and lines[-1].strip() == "```":
        lines = lines[:-1]  # remove closing ``` line
    corrected_code = "\n".join(lines)

# 4. Save the cleaned, corrected test file separately
with open("test_generated_v2.py", "w") as f:
    f.write(corrected_code)

print("Done! Review saved to review_report.md, corrected tests saved to test_generated_v2.py")